# Generated by Django 3.2.1 on 2021-05-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='user_upload',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
