# Generated by Django 3.2.2 on 2021-05-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_add_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actions_user',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
