# Generated by Django 3.2.2 on 2021-05-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210508_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_doc',
            old_name='created_date',
            new_name='create_datetime',
        ),
        migrations.AddField(
            model_name='add_doc',
            name='action_name',
            field=models.CharField(default='', max_length=50, verbose_name='Действие'),
        ),
    ]
