# Generated by Django 3.2.2 on 2021-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210508_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_doc',
            name='file_url',
            field=models.CharField(default='', max_length=50, verbose_name='Ссылка на документ'),
        ),
    ]
